version: '3.7'
services:
  geoip:
    image: cyborch/geoip:2.0.1-mongo
    build:
      context: service
    ports:
      - '3000:3000'
    environment:
      - NODE_CONFIG=development
    volumes:
      - './service:/opt/service'
    depends_on:
      - db

  db:
    image: bitnami/mongodb:4.0-debian-9
    environment:
      - DB_REMOTE_ROOT_NAME=root
      - DB_REMOTE_ROOT_PASS=devel
    ports:
      - '27017:27017'
    volumes:
      - './data:/bitnami/mongodb'
